-- 테이블에 있는 값을 삭제하란 뜻
--SET REFERENTIAL_INTEGRITY FALSE;
--truncate table user;
--truncate table product;
--truncate table option_tb;
--truncate table cart_tb;
--truncate table order_tb;
--SET REFERENTIAL_INTEGRITY TRUE;

insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cheese - Pont Couvert', 'Hansen and Sons', 107825);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Flour - Strong Pizza', 'Dare Group', 24964);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Skirt - 29 Foot', 'Kuhn Group', 214117);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bar Nature Valley', 'Ledner, Hoeger and Gulgowski', 35285);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beef - Rib Eye Aaa', 'Quigley-Jerde', 286900);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sugar - Icing', 'Rosenbaum, Von and Kulas', 139063);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Pastry - Cheese Baked Scones', 'Lind Group', 12394);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Madeira', 'Ernser, Runte and Wolf', 243979);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lime Cordial - Roses', 'Robel, Schmeler and Block', 288369);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sauce - Vodka Blush', 'Ankunding LLC', 57509);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Kippers - Smoked', 'Fisher-Greenfelder', 12056);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lobster - Tail 6 Oz', 'Gleason Inc', 154537);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Shrimp - 16/20, Peeled Deviened', 'Beer-Williamson', 102043);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Bouchard La Vignee Pinot', 'Legros LLC', 4248);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lemonade - Kiwi, 591 Ml', 'Parker LLC', 156851);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Appetizer - Chicken Satay', 'Block, Leuschke and Adams', 74163);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cinnamon - Ground', 'Schumm Inc', 240486);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beef - Striploin Aa', 'Herzog and Sons', 39382);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Sauvignon Blanc', 'Crona, Ziemann and Block', 222765);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Liquid Aminios Acid - Braggs', 'Ortiz, Brown and Schaden', 41624);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Clavet Saint Emilion', 'Hackett LLC', 70031);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bagelers - Cinn / Brown Sugar', 'Reilly and Sons', 293469);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Cake - Sheet Strawberry', 'Kuhn Inc', 140254);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Seabream Whole Farmed', 'Volkman-O''Kon', 292287);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Longos - Grilled Veg Sandwiches', 'Wiegand, Barrows and Mante', 241598);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Flour - Strong', 'Shields, Rolfson and Morissette', 11190);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Chianti Classica Docg', 'Okuneva-Anderson', 32107);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Broom Handle', 'Volkman Group', 156527);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Crush - Grape, 355 Ml', 'Emmerich-Boyer', 249868);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Water - Spring Water, 355 Ml', 'Goodwin-Littel', 92444);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread - Olive Dinner Roll', 'Beatty, Bayer and Schimmel', 183182);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Beer - Blue', 'Fadel and Sons', 81079);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Gatorade - Cool Blue Raspberry', 'Kilback, Bartell and Huel', 258232);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Crab - Blue, Frozen', 'Willms-Gulgowski', 164334);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Vermouth - White, Cinzano', 'Botsford-Walker', 146956);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lamb - Whole, Frozen', 'Crist-Bogan', 161109);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Puree - Mocha', 'Ebert, Kozey and Koch', 60274);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Magnotta, Merlot Sr Vqa', 'Gleichner Inc', 43388);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Bread Ww Cluster', 'Gulgowski Group', 77198);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Chateau Aqueria Tavel', 'Corwin-Stark', 293160);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Tray - 16in Rnd Blk', 'Skiles-Pfannerstill', 24185);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Magnotta, White', 'McKenzie, Larson and Reilly', 220700);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Horseradish Root', 'Kiehn LLC', 80716);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Lettuce - Radicchio', 'Kris-Johns', 164996);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Gherkin - Sour', 'Simonis, Beahan and Boyle', 124092);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Sprouts - Peppercress', 'Howe, Nitzsche and Watsica', 103848);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chocolate Liqueur - Godet White', 'Hickle, Weissnat and McLaughlin', 139513);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Wine - Red, Cabernet Sauvignon', 'Bergstrom-Leuschke', 132849);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Chips - Potato Jalapeno', 'Morissette, Okuneva and Conn', 108566);
insert into PRODUCT (image, product_name, description, price) values ('filepath/UUID/fileName', 'Apricots - Dried', 'Stanton-Jaskolski', 67895);

insert into user (roles, email, password) values ('ROLE_ADMIN', 'ghkden55@gmail.com', '{bcrypt}$2a$10$Em8W3/gpPhsNGafLVkNc4.U7vUsYqNeHwzfdflggGMnhf0ZZ2pa/e');
insert into user (roles, email, password) values ('ROLE_USER', 'bcurrington1@mlb.com', 'eA7+Ywu,pT%#?');
insert into user (roles, email, password) values ('ROLE_USER', 'kvanelli2@tamu.edu', 'pY0}q!eP');
insert into user (roles, email, password) values ('ROLE_USER', 'jsabates3@symantec.com', 'fP7%0\Uz4`{pI,');
insert into user (roles, email, password) values ('ROLE_USER', 'elaughlan4@sina.com.cn', 'vQ6''HLBx');
insert into user (roles, email, password) values ('ROLE_USER', 'ovosper5@berkeley.edu', 'vW0*rd1$');
insert into user (roles, email, password) values ('ROLE_USER', 'aloadwick6@booking.com', 'vW2,<B)`H3@<');
insert into user (roles, email, password) values ('ROLE_USER', 'eroseburgh7@youku.com', 'qZ4{LrW"qh');
insert into user (roles, email, password) values ('ROLE_USER', 'mconstant8@xinhuanet.com', 'aM5?C"''Wu');
insert into user (roles, email, password) values ('ROLE_USER', 'awilles9@odnoklassniki.ru', 'iL7{*xiY/A');


